### ISSUE TITLE
Plugin load failed - clean_css of undefined

### ISSUE THREAD

**Issue by akhatri** [bhaskarmelkani/hexo-asset-pipeline#1]
I've installed the package and when I start `hexo server` I get these errors at the beginning, although the server starts up

```
ERROR Plugin load failed: hexo-asset-pipeline
TypeError: Cannot read property 'clean_css' of undefined
    at /Users/ak/Documents/GitHub/website/node_modules/hexo-asset-pipeline/index.js:14:109
    at /Users/ak/Documents/GitHub/website/node_modules/hexo/lib/hexo/index.js:232:12
```

My package.json 

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.7"
  },
  "engines": {
    "node": "6.10"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-asset-pipeline": "^1.1.2",
    "hexo-autoprefixer": "^1.0.0",
    "hexo-browsersync": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-scss": "^1.0.2",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by bhaskarmelkani** [comment]
Hey,

Let me try to replicate the issue. Will get back ASAP.

**Comment by bhaskarmelkani** [comment]
It looks like you didn't  add `asset_pipeline` in the config file`_config.yml`. 
Its necessary to have it there, whether u use it or not.
_config.yaml
```yaml
## Add asset_pipeline 
asset_pipeline:
````
I have also added a check, so now its not necessary to have it there if you don't use it.

Postmortem:-
As hexo loads all the plugins that are mentioned in package.json and starts with 'hexo-', it was loading `hexo-asset-pipeline` and the package was breaking as there was no config for it in `_config.yaml`.

Hope this helps your issue.
