### ISSUE TITLE
robots.txt and humans.txt shouldn't be fingerprinted

### ISSUE THREAD

**Issue by tilsammans** [bhaskarmelkani/hexo-asset-pipeline#5]
Can I exclude them somewhere?

`humans-9ec36717bd07dd28f998a050986d02f9.txt` isn't gonna work. :)

**Comment by bhaskarmelkani** [comment]
Hey,

Yes I just added the config option to exclude files from revisioning.

I am publishing the change in some time.

**Comment by tilsammans** [comment]
Cool, thanks!

**Comment by bhaskarmelkani** [comment]
I have updated the changes, published new version **v1.2.5.**.

[README](https://github.com/bhaskarmelkani/hexo-asset-pipeline#revisioning).

**Comment by tilsammans** [comment]
Excellent! 👏👏👏

**Comment by bhaskarmelkani** [comment]
Closing the issue :)
